import mongoose from "mongoose";
import { connectToDatabase } from "./db.js";
import Item from "../model/Item.js";
import Category from "../model/Category.js";
import Table from "../model/Table.js";

async function seedData() {
  await connectToDatabase();

  try {
    // category
    const categoryToSeed = [
      { th: "ปลา" },
      { th: "กุ้ง" },
      { th: "ปลาหมึก" },
      { th: "ปู" },
      { th: "ไก่" },
      { th: "ผัด" },
      { th: "ข้าว" },
      { th: "เส้น" },
      { th: "ยำ" },
      { th: "ทานเล่น" },
      { th: "น้ำ" },
      { th: "ไข่" },
      { th: "สลัด" },
    ];
    const category = await Category.insertMany(categoryToSeed);

    // item
    const itemsToSeed = [
      {
        th: "ปลากระพงย่าง",
        en: "Grilled Sea Bass",
        rus: "снеппер гриль",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_001.png",
      },
      {
        th: "ปลาทับทิมย่าง",
        en: "Grilled Tilapia Fish",
        rus: "Тилапия рыба гриль",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_002.png",
      },
      {
        th: "ปลากระพงทอดน้ำปลา",
        en: "Deep-Fried Sea Bass with Fish Sauce",
        rus: "рыба жаренная снеппер политая рыбным соусом",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_003.png",
      },
      {
        th: "ปลาทับทิมทอดน้ำปลา",
        en: "Deep-Fried Tilapia Fish with Fish Sauce",
        rus: "рыба жареная тилапия политая рыбным соусом",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_004.png",
      },
      {
        th: "ปลากระพงทอดกระเทียม",
        en: "Deep-Fried Sea Bass with Garlic",
        rus: "рыба жаренная снеппер с чесноком",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_005.png",
      },
      {
        th: "ปลาทับทิมทอดกระเทียม",
        en: "Deep-Fried Tilapia Fish with Garlic",
        rus: "рыба жареная тилапия с чесноком",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_006.png",
      },
      {
        th: "ปลากระพงนึ่งมะนาว",
        en: "Steamed Sea Bass with Lime Sauce",
        rus: "рыба жаренная снеппер на пару с лимономэ ",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_007.png",
      },
      {
        th: "ปลาทับทิมนึ่งมะนาว",
        en: "Steamed Tilapia Fish with Lime Sauce",
        rus: "рыба жареная тилапия на пару с лимоном",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_008.png",
      },
      {
        th: "ปลากระพงสามรส",
        en: "Deep-Fried Sea Bass with 3 types of sauce (Sweet, Sour, Spicy Mixture) sauce can be separately",
        rus: "рыба жаренная снеппер с 3 видами соуса (сладкий,кислый,острый смесь) соус можно отдельно",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_009.png",
      },
      {
        th: "ปลากระพงแกงส้ม",
        en: "Sour curry with Sea Bass",
        rus: "Кислое карри с рыба сибасом",
        price: 250,
        category_id: category?.[0]._id,
        img: "img_010.png",
      },
      {
        th: "ปลาทับทิมแกงส้ม",
        en: "Sour curry with Tilapia Fish",
        rus: "кислый карри с рыба тилапия",
        price: 250,
        category_id: category?.[0]._id,
        img: "img_011.png",
      },
      {
        th: "ปลากระพงราดพริก (น้ำจิ้มแจ๋ว)",
        en: "Deep-Fried fish with Sea Bass with chili sauce (Spicy Sauce)",
        rus: "жаренная рыба сибасом с соусом Чили (острый соус)",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_012.png",
      },
      {
        th: "ปลาทับทิมราดพริก  (น้ำจิ้มแจ๋ว)",
        en: "Deep-Fried Tilapia Fish with Chili Sauce (Spicy Sauce)",
        rus: "жаренная рыба тилапия с соусом Чили (острый соус)",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_013.png",
      },
      {
        th: "ปลากระพงนึ่งซีอิ๋ว",
        en: "Steamed Sea Bass with Soy Sauce",
        rus: "рыба сибасом на пару в соевом соусе",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_014.png",
      },
      {
        th: "ปลาทับทิมนึ่งซีอิ๋ว",
        en: "Steamed Tilapia Fish with Soy Sauce",
        rus: "рыба тилапия на пару в соевом соусе",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_015.png",
      },
      {
        th: "ปลากระพงผัดพริกแกง",
        en: "Deep-Fried Sea Bass with Curry Paste",
        rus: "рыба сибасом жаренная кусочками с чёрным перцем",
        price: 350,
        category_id: category?.[0]._id,
        img: "img_016.png",
      },
      {
        th: "ปลาทับทิมผัดพริกแกง",
        en: "Deep-Fried Tilapia Fish with Curry Paste",
        rus: "рыба тилапия жаренная кусочками с чёрным перцем",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_017.png",
      },
      {
        th: "ปลากระพงผัดพริกไทยดำ",
        en: "Deep-Fried Sea Bass with Black Pepper",
        rus: "рыба сибасом жаренная кусочками с пастой Чили",
        price: 300,
        category_id: category?.[0]._id,
        img: "img_018.png",
      },
      {
        th: "กุ้งเผา",
        en: "Grilled Shrimp",
        rus: "креветки-гриль",
        price: 350,
        category_id: category?.[1]._id,
        img: "img_019.png",
      },
      {
        th: "กุ้งชุปแป้งทอด",
        en: "Batter-Fried Shrimp",
        rus: "Жареные креветки",
        price: 150,
        category_id: category?.[1]._id,
        img: "img_020.png",
      },
      {
        th: "กุ้งทอดกระเทียม",
        en: "Shrimp Fried with Garlic",
        rus: "креветки жаренные с чесноком",
        price: 150,
        category_id: category?.[1]._id,
        img: "img_021.png",
      },
      {
        th: "กุ้งอบเกลือ",
        en: "Shrimp Baked with Salt",
        rus: "креветки запечённые в соли",
        price: 280,
        category_id: category?.[1]._id,
        img: "img_022.png",
      },
      {
        th: "กุ้งอบวุ้นเส้น",
        en: "Baked Shrimp with Glass Noodles",
        rus: "Запеченные креветки со стеклянной лапшой",
        price: 180,
        category_id: category?.[1]._id,
        img: "img_023.png",
      },
      {
        th: "ทอดมันกุ้ง",
        en: "Deep-Fried Shrimp Cakes",
        rus: "Жареные креветки во фритюре",
        price: 180,
        category_id: category?.[1]._id,
        img: "img_024.png",
      },
      {
        th: "กุ้งแช่น้ำปลา",
        en: "Shrimp Marinated in Fish Sauce served with Separate Sauces (Not thermally processed)",
        rus: "креветки маринованные в рыбном соусе подаются с отдельными соусами (термически не обработанные)",
        price: 200,
        category_id: category?.[1]._id,
        img: "img_025.png",
      },
      {
        th: "กุ้งผัดซอสมะขาม",
        en: "Stir-Fried Shrimp with Tamarin Sauce",
        rus: "креветки жаренные с тамариновым соусом",
        price: 150,
        category_id: category?.[1]._id,
        img: "img_026.png",
      },
      {
        th: "กุ้งผัดพริกเผา",
        en: "Stir-Fried shrimp with Chili Paste",
        rus: "креветки жаренные с пастой чили",
        price: 180,
        category_id: category?.[1]._id,
        img: "img_027.png",
      },
      {
        th: "กุ้งโสร่ง",
        en: "Deep-Fried Wrapped Shrimps With Noodle",
        rus: "Креветки, завернутые во фритюр, с лапшой",
        price: 150,
        category_id: category?.[1]._id,
        img: "img_028.png",
      },
      {
        th: "กุ้งคั่วพริกเกลือ",
        en: "Stir-Fried Shrimp with Chili and Salt",
        rus: "Жареные креветки с чили и солью",
        price: 180,
        category_id: category?.[1]._id,
        img: "img_029.png",
      },
      {
        th: "ต้มยำกุ้ง",
        en: "Shrimp Tom Yum Soup",
        rus: "том-ям с креветки",
        price: 160,
        category_id: category?.[1]._id,
        img: "img_030.png",
      },
      {
        th: "ปลาหมึกย่าง",
        en: "Grilled Squid",
        rus: "кальмар-гриль",
        price: 250,
        category_id: category?.[2]._id,
        img: "img_031.png",
      },
      {
        th: "ปลาหมึกทอดกระเทียม",
        en: "Fried Squid with Garlic",
        rus: "кальмар-гриль с чесноком",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_032.png",
      },
      {
        th: "ปลาหมึกนึ่งมะนาว",
        en: "Steamed Squid with Lime Sauce",
        rus: "кальмар на пару с лимоном",
        price: 180,
        category_id: category?.[2]._id,
        img: "img_033.png",
      },
      {
        th: "ปลาหมึกชุปแป้งทอด",
        en: "Batter Fried Squid",
        rus: "Жареный кальмар",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_034.png",
      },
      {
        th: "ปลาหมึกผัดไข่เค็ม",
        en: "Stir-Fried Squid with Salted Egg",
        rus: "Жареный кальмар с соленым яйцом",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_035.png",
      },
      {
        th: "ปลาหมึกผัดผงกะหรี่",
        en: "Stir-Fried Squid with Curry Powder",
        rus: "кальмар жаренный с карри-мукой",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_036.png",
      },
      {
        th: "ปลาหมึกผัดพริกเผา",
        en: "Stir-Fried Squid with Chili Paste",
        rus: "кальмар жаренный с Соус-чили",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_037.png",
      },
      {
        th: "ปลาหมึกผัดพริกไทยดำ",
        en: "Stir-Fried Squid with Black Pepper",
        rus: "кальмар жареный с черным перцем",
        price: 150,
        category_id: category?.[2]._id,
        img: "img_038.png",
      },
      {
        th: "ปลาหมึกต้ม",
        en: "Boiled Squid",
        rus: "вареный кальмар",
        price: 160,
        category_id: category?.[2]._id,
        img: "img_039.png",
      },
      {
        th: "ปูนึ่ง",
        en: "Steamed Crab",
        rus: "краб на пару",
        price: 200,
        category_id: category?.[3]._id,
        img: "img_040.png",
      },
      {
        th: "ปูเผา",
        en: "Grilled Crab",
        rus: "краб-гриль",
        price: 200,
        category_id: category?.[3]._id,
        img: "img_041.png",
      },
      {
        th: "ปูผัดพริกไทยดำ",
        en: "Stir-Fried Crab with Black Pepper",
        rus: "краб жаренный с чёрным перцем",
        price: 250,
        category_id: category?.[3]._id,
        img: "img_042.png",
      },
      {
        th: "ปูผัดผงกะหรี่",
        en: "Stir-Fried Crab with Curry Powder",
        rus: "жаренный краб с карри-мукой",
        price: 250,
        category_id: category?.[3]._id,
        img: "img_043.png",
      },
      {
        th: "ปูผัดน้ำพริกเผา",
        en: "Stir-Fried Crab with Chili Paste",
        rus: "жаренный краб с пастой Чили",
        price: 250,
        category_id: category?.[3]._id,
        img: "img_044.png",
      },
      {
        th: "ไก่ผัดเม็ดมะม่วง",
        en: "Stir-Fried Chicken with Cashew Nuts (Not spicy)",
        rus: "цыпленок жареный с орехами кешью (не острый)",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_045.png",
      },
      {
        th: "ไก่ผัดกระเพรา",
        en: "Stir-Fried Chicken with Basil",
        rus: "курица жареная с базиликом",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_046.png",
      },
      {
        th: "ไก่ทอดกระเทียม",
        en: "Chicken Fried with Garlic",
        rus: "курица жаренная с чесноком",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_047.png",
      },
      {
        th: "แกงเขียวหวานไก่",
        en: "Green Curry Chicken",
        rus: "зелёный карри с курицей",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_048.png",
      },
      {
        th: "ต้มข่าไก่",
        en: "Thai Chicken Coconut Soup",
        rus: "том-ка с курицей",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_049.png",
      },
      {
        th: "ต้มยำไก่",
        en: "Chicken Tom Yum Soup",
        rus: "том-ям с курицей",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_050.png",
      },
      {
        th: "แกงมัสมั่น",
        en: "Massaman Curry With Chicken",
        rus: "красный карри с курицей",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_051.png",
      },
      {
        th: "แกงจืด",
        en: "Tofu Soup with Chicken and Vegetables",
        rus: "суп с тофу на выбор курица и овощами",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_052.png",
      },
      {
        th: "ต้มแซ่บ",
        en: "Tom Sab (Like Tom Yum, but dry chili added)",
        rus: "том-сэб (как том-ям,но перец Чили добавляют сухой)",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_053.png",
      },
      {
        th: "ไก่ผัดพริกเผา ",
        en: "Stir-Fried Chicken with Chili Paste",
        rus: "цыпленок жареный  с пастой чили",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_054.png",
      },
      {
        th: "ไก่ผัดน้ำมันหอย",
        en: "Stir-Fried Chicken with Oyster Sauce",
        rus: "Жареная курица с устричным соусом",
        price: 150,
        category_id: category?.[4]._id,
        img: "img_055.png",
      },
      {
        th: "ผัดผัก",
        en: "Stir-Fried Mix Vegetables",
        rus: "Жареная смесь овощей",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_056.png",
      },
      {
        th: "ผัดเห็ดเข็มทอง",
        en: "Stir-Fried White Mushrooms (Golden Needle)",
        rus: "жаренные мелкие местные белые грибы(золотая игла)",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_057.png",
      },
      {
        th: "ผัดผักกระเฉดไฟแดง",
        en: "Stir-Fried Mimosa (On High Heat)",
        rus: "Жареная мимоза (на сильном огне)",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_058.png",
      },
      {
        th: "ผัดผักบุ้งไฟแดง",
        en: "Stir-Fried Morning-Glory (On High Heat)",
        rus: "Жареная ипомея (на сильном огне)",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_059.png",
      },
      {
        th: "ผัดคะน้ากุ้งสด",
        en: "Stir-Fried Chinese Cabbage with Shrimp",
        rus: "жаренная китайская капуста с креветками",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_060.png",
      },
      {
        th: "ผัดคะน้าปลาเค็ม",
        en: "Stir-Fried Chinese Cabbage with Salted Dry Fish",
        rus: "жаренная китайская капуста с солёной сухой рыбой",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_061.png",
      },
      {
        th: "ผักเหมียงผัดไข่",
        en: "Local Fried Herb with Egg (Must Try)",
        rus: "местная жаренная трава жаренная с яйцом(нужно попробовать )",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_062.png",
      },
      {
        th: "ถั่วงอกผัดน้ำมันหอย",
        en: "Stir-Fried Bean Sprouts with Oyster Sauce",
        rus: "жареные ростки фасоли с устричным соусом",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_063.png",
      },
      {
        th: "ต้นอ่อนทานตะวันผัดน้ำมันหอย",
        en: "Stir-Fried Sunflower Sprouts with Oyster Sauce",
        rus: "жареные ростки подсолнуха с устричным соусом",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_064.png",
      },
      {
        th: "กะหล่ำปลีผัดน้ำมันหอย",
        en: "Stir-Fried Cabbage with Oyster Sauce.",
        rus: "жареные капуста фасоли с устричным соусом",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_065.png",
      },
      {
        th: "บล็อคโคลี่ผัดน้ำมันหอย",
        en: "Stir-Fried Broccoli with Oyster Sauce.",
        rus: "жареная брокколи с устричным соусом.",
        price: 100,
        category_id: category?.[5]._id,
        img: "img_066.png",
      },
      {
        th: "ข้าวผัดกุ้ง",
        en: "Fried Rice with Shrimp",
        rus: "жареный рис с креветками",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_067.png",
      },
      {
        th: "ข้าวผัดไก่",
        en: "Fried Rice with Chicken",
        rus: "жареный рис с курицей",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_068.png",
      },
      {
        th: "ข้าวผัดหมึก",
        en: "Fried Rice with Squid ",
        rus: "жареный рис с кальмарами",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_069.png",
      },
      {
        th: "ข้าวผัดกระเพรา (ไก่, กุ้ง, ปลาหมึก, ซีฟู๊ด)",
        en: "Fried Rice with Basil (Chicken, Shrimp, Squid or Seafood)",
        rus: "жаренный рис с базиликом(курица,креветки,кальмар или морепродукты)",
        price: 150,
        category_id: category?.[6]._id,
        img: "img_070.png",
      },
      {
        th: "ข้าวผัดเขียวหวาน (ไก่, ปลา)",
        en: "Fried Rice with Green Curry (Chicken or Fish)",
        rus: "жаренный рис с зелёным карри (курица или рыба)",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_071.png",
      },
      {
        th: "ข้าวผัดสัปรด",
        en: "Fried Rice with Pineapple",
        rus: "жаренный рис с ананасом",
        price: 150,
        category_id: category?.[6]._id,
        img: "img_072.png",
      },
      {
        th: "ข้าวผัดกระเทียมพริกไทย",
        en: "Fried Rice with Garlic and Black Pepper",
        rus: "жаренный рис с чесноком",
        price: 100,
        category_id: category?.[6]._id,
        img: "img_073.png",
      },
      {
        th: "ข้าวผัดน้ำพริกเผา",
        en: "Fried Rice with Chilli Paste",
        rus: "жареный рис с пастой чили",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_074.png",
      },
      {
        th: "ข้าวผัดเครื่องแกง (กุ้ง, ปลา, ซีฟู๊ด, ไก่)",
        en: "Fried Rice with Red Curry (Shrimp, Fish or Seafood)",
        rus: "жаренный рис с красным карри(креветки ,рыба или морепродукты )",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_075.png",
      },
      {
        th: "ข้าวสวย",
        en: "Streamed Rice",
        rus: "варенный рис",
        price: 20,
        category_id: category?.[6]._id,
        img: "img_076.png",
      },
      {
        th: "ข้าวผัดต้มยำ",
        en: "Tom Yum Fried Rice",
        rus: "Том Ям жареный рис",
        price: 120,
        category_id: category?.[6]._id,
        img: "img_077.png",
      },
      {
        th: "ผัดก๋วยเตี๋ยวไก่",
        en: "Stir-Fried Noodles with Chicken (Wide Rice Noodles)",
        rus: "жаренная лапша с курица (крупная )",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_078.png",
      },
      {
        th: "ผัดก๋วยเตี๋ยวกุ้ง",
        en: "Stir-Fried Noodles with Shrimp (Wide Rice Noodles)",
        rus: "жаренная лапша с креветка (крупная )",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_079.png",
      },
      {
        th: "ผัดบะหมี่เหลือง",
        en: "Stir-Fried Yellow Noodles",
        rus: "жаренная жёлтая лапша",
        price: 120,
        category_id: category?.[7]._id,
        img: "img_080.png",
      },
      {
        th: "สปาเก็ตตี้เนย",
        en: "Spaghetti with Butter",
        rus: "cпагетти со сливочным маслом",
        price: 120,
        category_id: category?.[7]._id,
        img: "img_081.png",
      },
      {
        th: "สปาเก็ตตี้เนยไก่",
        en: "Spaghetti with Chicken and Butter",
        rus: "cпагетти с курицей и маслом",
        price: 120,
        category_id: category?.[7]._id,
        img: "img_082.png",
      },
      {
        th: "สปาเก็ตตี้เนยกุ้ง",
        en: "Spaghetti with Chicken and Butter",
        rus: "cпагетти с креветками и сливочным маслом",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_083.png",
      },
      {
        th: "ผัดวุ้นเส้น",
        en: "Stir-Fried Glass Noodles",
        rus: "жаренная стеклянная лапша",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_084.png",
      },
      {
        th: "ผัดไทไก่",
        en: "Pad Thai (Fried Noodle Thai style with Chicken)",
        rus: "пад-тай с курица ",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_085.png",
      },
      {
        th: "ผัดไทกุ้งสด",
        en: "Pad Thai (Fried Noodle Thai style with Prawns)",
        rus: "пад-тай с креветками",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_086.png",
      },
      {
        th: "ผัดไทซีฟู๊ด",
        en: "Pad Thai (Fried Noodle Thai style with Seafood)",
        rus: "пад-тай с морепродуктами",
        price: 150,
        category_id: category?.[7]._id,
        img: "img_087.png",
      },
      {
        th: "ผัดบะหมี่ี่กึ่งสำเร็จรูป",
        en: "Stir Fried Instant Noodles with Oyster Sauce.",
        rus: "жареная лапша быстрого приготовления с устричным соусом.",
        price: 100,
        category_id: category?.[7]._id,
        img: "img_088.png",
      },
      {
        th: "ยำซีฟู๊ด",
        en: "Seafood Salad",
        rus: "салат из морепродуктов",
        price: 150,
        category_id: category?.[8]._id,
        img: "img_089.png",
      },
      {
        th: "ยำวุ้นเส้นไก่",
        en: "Glass Noodles Salad with Chicken",
        rus: "стакан Салат с курицей",
        price: 150,
        category_id: category?.[8]._id,
        img: "img_090.png",
      },
      {
        th: "ยำวุ้นเส้นกุ้ง",
        en: "Glass Noodles Salad with Shrimp",
        rus: "стакан Салат с креветками",
        price: 150,
        category_id: category?.[8]._id,
        img: "img_091.png",
      },
      {
        th: "ยำผักกูด",
        en: "Spicy Vegetable Salad",
        rus: "острый овощной салат",
        price: 150,
        category_id: category?.[8]._id,
        img: "img_092.png",
      },
      {
        th: "ยำข้าวโพด",
        en: "Spicy Corn Salad",
        rus: "острый кукурузный салат",
        price: 150,
        category_id: category?.[8]._id,
        img: "img_093.png",
      },
      {
        th: "ยำมะม่วง",
        en: "Mango Salad",
        rus: "салат из манго",
        price: 120,
        category_id: category?.[8]._id,
        img: "img_094.png",
      },
      {
        th: "เฟรนฟาย",
        en: "French Fries",
        rus: "картофель-фри",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_095.png",
      },
      {
        th: "นักเก็ตไก่",
        en: "Nuggets",
        rus: "самородки",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_096.png",
      },
      {
        th: "ขนมปังทอดเนย",
        en: "Butter Bread",
        rus: "масло хлеб",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_097.png",
      },
      {
        th: "ขนมปังทอดกระเทียม",
        en: "Garlic Bread",
        rus: "чесночный хлеб",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_098.png",
      },
      {
        th: "หัวหอมทอด",
        en: "Onion Rings",
        rus: "луковые кольца",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_099.png",
      },
      {
        th: "เห็ดทอด",
        en: "Crispy Mushroom",
        rus: "хрустящий гриб",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_100.png",
      },
      {
        th: "เกี๊ยวทอด",
        en: "Fried Dumplings",
        rus: "жареные пельмени",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_101.png",
      },
      {
        th: "ปีกไก่ทอด",
        en: "Fried Chicken Wings",
        rus: "жареные куриные крылышки",
        price: 100,
        category_id: category?.[9]._id,
        img: "img_102.png",
      },
      {
        th: "ซุปเห็ด",
        en: "Mushroom Cream Soup",
        rus: "грибной крем-суп",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_103.png",
      },
      {
        th: "ซุุปข้าวโพด",
        en: "Corn Cream Soup",
        rus: "кукурузный крем-суп",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_104.png",
      },
      {
        th: "เกี๊ยว",
        en: "dumpling",
        rus: "Пельмени",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_105.png",
      },
      {
        th: "ไข่เจียว",
        en: "omelet",
        rus: "омлет",
        price: 100,
        category_id: category?.[11]._id,
        img: "img_117.png",
      },
      {
        th: "ไข่เจียวไก่",
        en: "chicken omelet",
        rus: "куриный омлет",
        price: 150,
        category_id: category?.[11]._id,
        img: "img_118.png",
      },
      {
        th: "ไข่เจียวปู",
        en: "crab Omelet",
        rus: "крабовый омлет",
        price: 150,
        category_id: category?.[11]._id,
        img: "img_119.png",
      },
      {
        th: "ไข่เจียวปููอัด",
        en: "crab Stick Omelet",
        rus: "крабовые палочки омлет",
        price: 100,
        category_id: category?.[11]._id,
        img: "img_120.png",
      },
      {
        th: "ไข่เจียวซีฟู้ด",
        en: "seafood Omelet",
        rus: "омлет из морепродуктов",
        price: 150,
        category_id: category?.[11]._id,
        img: "img_121.png",
      },
      {
        th: "สลัดผัก",
        en: "Mix Salad",
        rus: "Микс-салат",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_107.png",
      },
      {
        th: "สลัดผลไม้",
        en: "Fruit Salad",
        rus: "Фруктовый салат",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_108.png",
      },
      {
        th: "สลัดกุ้ง",
        en: "Shrimp Salad",
        rus: "Салат с креветками",
        price: 120,
        category_id: category?.[12]._id,
        img: "img_109.png",
      },
      {
        th: "สลัดไก่กรอบ",
        en: "Crispy Chicken Salad",
        rus: "Салат с хрустящей курицей",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_110.png",
      },
      {
        th: "สลัดอกไก่",
        en: "Chicken Breast Salad",
        rus: "Салат с куриной грудкой",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_111.png",
      },
      {
        th: "สลัดอกไก่พริกไทยดำ",
        en: "Black Pepper Chicken Breast Salad",
        rus: "Салат из куриной грудки с черным перцем",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_112.png",
      },
      {
        th: "สลัดไข่ต้ม ",
        en: "Boiled Egg Salad",
        rus: "Салат из вареных яиц",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_113.png",
      },
      {
        th: "สลัดซีซาร์",
        en: "Caesar salad",
        rus: "Салат Цезарь",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_114.png",
      },
      {
        th: "สลัดปูอัด",
        en: "Crab Stick Salad",
        rus: "Салат из крабовых палочек",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_115.png",
      },
      {
        th: "สลัดโรลปูอัด",
        en: "Crab Stick Salad Roll with Spicy Seafood Mayonnaise",
        rus: "Салатный рулет из крабовых палочек с пикантным майонезом из морепродуктов",
        price: 100,
        category_id: category?.[12]._id,
        img: "img_116.png",
      },
      {
        th: "ไก่ผสมมันบดทอด",
        en: "Fried Chicken with Mashed Potatoes",
        rus: "котлеты",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_106.png",
      },
      {
        th: "มันฝรั่งบด",
        en: "mashed potatoes",
        rus: "картошка пюре",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_107.png",
      },
      {
        th: "ซุปบอร์ชท์",
        en: "Borscht Soup",
        rus: "суп Борщ",
        price: 120,
        category_id: category?.[9]._id,
        img: "img_108.png",
      },
      {
        th: "น้ำเปล่า",
        en: "Mineral Water",
        rus: "минеральная вода",
        price: 20,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำผลไม้ปั่น",
        en: "Mix Fruit Smoothie",
        rus: "шейк-фрукты",
        price: 100,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำแตงโมปั่น",
        en: "Watermelon Smoothie",
        rus: "шейк-арбуз",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำสัปรดปั่น",
        en: "Pineapple Smoothie",
        rus: "шейк-ананас",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำมะพร้าว",
        en: "Coconut Water",
        rus: "кокос",
        price: 60,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำมะพร้าวปั่น",
        en: "Coconut Smoothie",
        rus: "шейк-кокос",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำกล้วยปั่น",
        en: "Banana Smoothie",
        rus: "шейк-банан",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำมะม่วงปั่น",
        en: "Mango Smoothie",
        rus: "шейк-манго",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำมะนาวปั่น",
        en: "Lemonade Smoothie",
        rus: "шейк-лимонад",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำส้มปั่น",
        en: "Orange Smoothie",
        rus: "шейк-апельсин",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำส้มคั้น",
        en: "Orange Juice",
        rus: "апельсиновый сок",
        price: 100,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำแอปเปิ้ลปั่น",
        en: "Apple Smoothie",
        rus: "шейк-яблоко",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำแก้วมังกรปั่น",
        en: "Dragon Fruit Smoothie",
        rus: "шейк-Драконий фрукт",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "น้ำองุ่นปั่น",
        en: "Grape Smoothie",
        rus: "шейк-Виноград",
        price: 80,
        category_id: category?.[10]._id,
      },
      {
        th: "โค้ก",
        en: "Coca-Cola",
        rus: "Кока-Кола",
        price: 40,
        category_id: category?.[10]._id,
      },
      {
        th: "เป๊ปซี่",
        en: "Pepsi",
        rus: "пепси",
        price: 40,
        category_id: category?.[10]._id,
      },
      {
        th: "แฟนต้าน้ำแดง",
        en: "Fanta Raspberry",
        rus: "фанта малина",
        price: 40,
        category_id: category?.[10]._id,
      },
      {
        th: "แฟนต้าน้ำส้ม",
        en: "Fanta Orange",
        rus: "фруктовый пунш фанта",
        price: 40,
        category_id: category?.[10]._id,
      },
      {
        th: "แฟนต้าน้ำเขียว",
        en: "Fanta Fruit Punch",
        rus: "",
        price: 40,
        category_id: category?.[10]._id,
      },
      {
        th: "สไปรท์",
        en: "Sprite",
        rus: "спрайт",
        price: 40,
        category_id: category?.[10]._id,
      },
    ];
    await Item.insertMany(itemsToSeed);

    // table
    const tableToSeed = [
      { table: "A01" },
      { table: "A02" },
      { table: "A03" },
      { table: "A04" },
      { table: "A05" },
      { table: "A06" },
    ];
    await Table.insertMany(tableToSeed);

    console.log("Database seeded with sample data");
  } catch (error) {
    console.error("Error seeding database:", error.message);
  } finally {
    await mongoose.disconnect();
    console.log("Database connection closed");
  }
}

seedData();
